### PR TITLE
Remove broken name from config

### PR DESCRIPTION
**Pull request by mikebcbc**
This name breaks this config since it's not named above. This PR removes the name from this file so it's easier to copy + paste.

### CODE REVIEW

**Comment by bladehstream** [comment]
Agree 100% with this change; it's required to make the config work correctly.

**Comment by DaVinci-10** [comment]
Guys, Please update your example config to complete the last change. if your going to call it by name in `[resonence_tester]` then it needs to be named that way `[adxl345 usbadxl]`
```
[adxl345 usbadxl]
cs_pin: PIS:gpio13
#spi_bus: spi1a
spi_software_sclk_pin: PIS:gpio10
spi_software_mosi_pin: PIS:gpio11
spi_software_miso_pin: PIS:gpio12
axes_map: x,-z,y

[resonance_tester]
#accel_chip: adxl345
accel_chip: adxl345 usbadxl
probe_points:
    100,100,20
...
```

**Comment by bistory** [comment]
@GerogeFu Please do this, a lot of newbies are falling into that trap and ask for help ;-)

**Comment by jakebullet70** [comment]
This NEEDS TO BE merged!!!!!!!!!!!!!

**Comment by StdVectorBool** [comment]
@eliwong Could you handle the merge?

**Pull request merged**
